<!-- ════════════════════════════════════════════════════════════
     MODULE 8: REPORTS
     ════════════════════════════════════════════════════════════ -->
<div id="sec-reports" class="dash-section <?=($active_tab==='reports')?'active':''?>">

  <div class="sec-header">
    <h2><i class="fas fa-file-export"></i> Reports</h2>
  </div>

  <div class="cards-grid" style="margin-bottom:2rem;">
    <?php foreach([
      ['inventory_status','Medicine Inventory Status','fa-pills','Full inventory report with stock levels, expiry dates, and values','success'],
      ['dispensing_records','Dispensing Records','fa-hand-holding-medical','All dispensing activity by date range, patient, or medicine','primary'],
      ['stock_transactions','Stock Transaction History','fa-exchange-alt','Restock, adjustments, returns, and expired removals','info'],
      ['alert_summary','Alert Summary','fa-triangle-exclamation','Low stock, out of stock, and expiry alerts','warning'],
      ['purchase_orders','Purchase Orders','fa-file-invoice','All purchase orders with supplier and delivery status','primary'],
      ['supplier_report','Supplier Report','fa-truck','Supplier details, performance, and order history','info'],
      ['prescription_fulfillment','Prescription Fulfillment','fa-prescription','Rx completion rates — dispensed vs pending vs cancelled','success'],
      ['analytics_summary','Analytics Summary','fa-chart-bar','Comprehensive overview of all pharmacy metrics','warning'],
    ] as [$type,$title,$icon,$desc,$color]):?>
    <div class="info-card" style="cursor:pointer;" onclick="openReportModal('<?=$type?>','<?=$title?>')">
      <div style="display:flex;align-items:center;gap:1rem;margin-bottom:1rem;">
        <div style="width:48px;height:48px;border-radius:12px;background:var(--<?=$color?>-light);color:var(--<?=$color?>);display:flex;align-items:center;justify-content:center;font-size:1.4rem;"><i class="fas <?=$icon?>"></i></div>
        <h4 style="font-size:1.4rem;font-weight:700;"><?=$title?></h4>
      </div>
      <p style="font-size:1.2rem;color:var(--text-secondary);"><?=$desc?></p>
      <div style="margin-top:1rem;display:flex;gap:.5rem;">
        <span class="adm-badge adm-badge-info" style="font-size:.9rem;">PDF</span>
        <span class="adm-badge adm-badge-success" style="font-size:.9rem;">CSV</span>
        <span class="adm-badge adm-badge-primary" style="font-size:.9rem;">XLSX</span>
      </div>
    </div>
    <?php endforeach;?>
  </div>

  <!-- Recent Reports -->
  <?php
    $recent_reports=[];
    $q=mysqli_query($conn,"SELECT pr.*, u.name AS generated_by_name FROM pharmacy_reports pr JOIN users u ON pr.generated_by=u.id ORDER BY pr.generated_at DESC LIMIT 10");
    if($q) while($r=mysqli_fetch_assoc($q)) $recent_reports[]=$r;
  ?>
  <?php if(!empty($recent_reports)):?>
  <div class="adm-card" style="padding:1.8rem;">
    <h3 style="font-size:1.4rem;font-weight:700;margin-bottom:1rem;"><i class="fas fa-history" style="color:var(--role-accent);margin-right:.5rem;"></i>Recently Generated Reports</h3>
    <div class="adm-table-wrap">
      <table class="adm-table">
        <thead><tr><th>Report Type</th><th>Format</th><th>Generated By</th><th>Date</th><th>Action</th></tr></thead>
        <tbody>
        <?php foreach($recent_reports as $rpt):?>
        <tr>
          <td><strong><?=ucwords(str_replace('_',' ',$rpt['report_type']))?></strong></td>
          <td><span class="adm-badge adm-badge-<?=$rpt['format']==='PDF'?'danger':($rpt['format']==='CSV'?'success':'primary')?>"><?=$rpt['format']?></span></td>
          <td><?=htmlspecialchars($rpt['generated_by_name'])?></td>
          <td><?=date('d M Y, g:i A',strtotime($rpt['generated_at']))?></td>
          <td>
            <?php if($rpt['file_path']):?>
            <a href="/RMU-Medical-Management-System/<?=htmlspecialchars($rpt['file_path'])?>" class="btn-icon btn btn-primary btn-sm" download><span class="btn-text"><i class="fas fa-download"></i> Download</span></a>
            <?php else:?>—<?php endif;?>
          </td>
        </tr>
        <?php endforeach;?>
        </tbody>
      </table>
    </div>
  </div>
  <?php endif;?>
</div>

<!-- ══ Report Generation Modal ══ -->
<div class="modal-bg" id="modalReport">
  <div class="modal-box">
    <div class="modal-header"><h3><i class="fas fa-file-export" style="color:var(--primary);"></i> <span id="reportTitle">Generate Report</span></h3><button class="btn btn-primary modal-close" onclick="closeModal('modalReport')"><span class="btn-text">&times;</span></button></div>
    <form onsubmit="submitReport(event)">
      <input type="hidden" name="report_type" id="reportType">
      <div class="form-row">
        <div class="form-group"><label>Start Date</label><input type="date" class="form-control" name="start_date" value="<?=date('Y-m-01')?>"></div>
        <div class="form-group"><label>End Date</label><input type="date" class="form-control" name="end_date" value="<?=date('Y-m-d')?>"></div>
      </div>
      <div class="form-group"><label>Export Format *</label>
        <select class="form-control" name="format" required>
          <option value="PDF">PDF</option>
          <option value="CSV">CSV</option>
          <option value="XLSX">Excel (XLSX)</option>
        </select>
      </div>
      <button type="submit" class="btn-icon btn btn-primary" style="width:100%;justify-content:center;"><span class="btn-text"><i class="fas fa-download"></i> Generate & Download</span></button>
    </form>
  </div>
</div>

<script>
function openReportModal(type,title){
  document.getElementById('reportType').value=type;
  document.getElementById('reportTitle').textContent='Generate '+title;
  openModal('modalReport');
}

async function submitReport(e){
  e.preventDefault();
  const fd=Object.fromEntries(new FormData(e.target));
  fd.action='generate_report';
  const r=await pharmAction(fd);
  if(r.success){
    toast(r.message||'Report generated');
    closeModal('modalReport');
    if(r.download_url) window.open(r.download_url,'_blank');
    setTimeout(()=>location.reload(),1500);
  } else toast(r.message||'Error generating report','danger');
}
</script>
