ALTER TABLE lab_technicians
ADD COLUMN IF NOT EXISTS institution_attended VARCHAR(200) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS graduation_year INT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS postgraduate_details TEXT DEFAULT NULL;

ALTER TABLE lab_technician_settings
ADD COLUMN IF NOT EXISTS 
otif_stat_order TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS 
otif_reagent_expiry TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS 
otif_result_amend TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS 
otif_license_expiry TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS 
otif_shift_reminder TINYINT(1) DEFAULT 1,
ADD COLUMN IF NOT EXISTS preferred_channel VARCHAR(50) DEFAULT 'In-Dashboard';
